src/LaunchDarkly/EventProcessor.php, src/LaunchDarkly/LDClient.php, src/LaunchDarkly/LDUser.php
This approach uses `pfsockopen` to open a persistent socket connection.
=> Record events with PHP

.gitignore, circle.yml, composer.json, composer.lock, integration-tests/LDDFeatureRequesterTest.php, integration-tests/README.txt, integration-tests/Vagrantfile, integration-tests/bootstrap.sh, integration-tests/composer.json, src/LaunchDarkly/ApcLDDFeatureRequester.php, src/LaunchDarkly/EventProcessor.php, src/LaunchDarkly/FeatureRep.php, src/LaunchDarkly/FeatureRequester.php, src/LaunchDarkly/GuzzleFeatureRequester.php, src/LaunchDarkly/LDClient.php, src/LaunchDarkly/LDDFeatureRequester.php, src/LaunchDarkly/LDDFeatureRetriever.php, src/LaunchDarkly/LDUser.php, src/LaunchDarkly/LDUserBuilder.php, src/LaunchDarkly/TargetRule.php, src/LaunchDarkly/Variation.php, tests/FeatureRepTest.php, tests/LDClientTest.php, tests/LDUserTest.php
* Clean up formatting and add types
* New FeatureRequester interface to abstract grizzly and ldd support
* Support PHP 5.3
* New optional predis for LDD retrieval
More tests, specifically LDD, to come
=> Support LDD feature retrieval

README.md, circle.yml, composer.json, composer.lock
Initial PR to make Guzzle 5 a suggestion rather than a requirement. Intending to follow up with a Guzzle 6 compatible implementation of the Feature Requester.
=> Make Guzzle 5 a suggestion not a requirement

src/LaunchDarkly/GuzzleFeatureRequester.php
This change is not why the v1 restwrapper was failing, but should happen anyway.
=> switch back to getting /flags instead of /latest-flags

composer.json
We use monolog as the default logger, but weren't explicitly requiring it.
=> Add monolog as a required dependency

CONTRIBUTING.md, circle.yml, composer.json, composer.lock, src/LaunchDarkly/Clause.php, src/LaunchDarkly/FeatureFlag.php, src/LaunchDarkly/LDClient.php, src/LaunchDarkly/Rule.php, src/LaunchDarkly/VariationOrRollout.php, tests/LDClientTest.php, tests/OperatorsTest.php
This is now working with PHP 5.3.25
=> Fix PHP 5.3 incompatibilities

src/LaunchDarkly/FeatureFlag.php, src/LaunchDarkly/LDClient.php
Since now it didn't change if you had your toggle Off or On with false, as both options where returning null when asking for the variant value. It happens that null is not exactly the same as false, this fixes it and now properly returns a false when it's false. This problem also happened when any of your multivariant values was a false too
Hope we can fix this, as we need it for properly A/B testing 😄
=> Fixing variant retrieving when toggle is off

circle.yml, composer.json
install php55-php71 with docker. run tests after installing minimum and maximum dependency versions allowed by composer config.
this is one of two competing solutions to my Travis CI solution:
#46
here is a sample build:
https://circleci.com/gh/abacaphiliac/php-client/21
it gets the job done in ~10 minutes which is a significant improvement over my phpbrew CircleCI solution:
#50 
this one is better than #50, but still not quite as good as the machine-parallelized matrix builds of TravisCI which accomplishes the same goal but in ~5 minutes:
https://travis-ci.org/abacaphiliac/php-client/builds/184626287
@drichelson please let me know what you think about these solutions and which one(s) you would like me to explore further.
=> build on php55-php71 via docker

integration-tests/composer.json
```
07:20 $ 
✔ ~/github.com/launchdarkly/php-client/integration-tests [circle-docker-cleanup ↓·1↑·1|✔] 
07:20 $ vagrant destroy && vagrant up && vagrant ssh
default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Destroying VM and associated drives...
==> default: [vagrant-hostsupdater] Removing hosts
==> default: Running cleanup tasks for 'shell' provisioner...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20161214.0.0'. The latest is version '20161214.0.1'. Run
==> …
```
=> add monolog to integration-test composer config.

circle.yml
this makes our docker builds look a little more sane.
=> simplify docker build commands.

circle.yml, integration-tests/LDDFeatureRequesterTest.php, integration-tests/Vagrantfile, integration-tests/bootstrap.sh, integration-tests/bootstrap.user.sh, src/LaunchDarkly/ApcLDDFeatureRequester.php, src/LaunchDarkly/ApcuLDDFeatureRequester.php, src/LaunchDarkly/LDClient.php
depends on #56 and #57 .
first of all, i apologize sincerely for the nesting-doll pull-requests. it is suboptimal but i think that isolating the previous submissions lessens the cognitive load of this one, my coup de grace.
* add APCu Feature Requester, with documentation indicating that it should be preferred over APC
* @deprecate the APC Feature Requester since APC is a dead extension (per the docs)
* skip APC integration test if APC is not installed
* add APCu integration test, and skip if APCu is not installed
* run integration tests on php56 in CircleCI (where APC and APCu are both available)
* enable APC in the Vagrant VM php55 installation
* ensure integration tests pass in Vagrant VM on php54 AND php55
```
vagrant@vagrant-ubuntu-trusty-64:~/project/integration-tests$ php -v && …
```
=> add integration tests to CircleCI

src/LaunchDarkly/FeatureFlag.php, tests/FeatureFlagTest.php
fix `WARNING: array_map(): Argument #2 should be an array in vendor/launchdarkly/launchdarkly-php/src/LaunchDarkly/FeatureFlag.php on line 60` where FeatureFlag assumes `prerequisites` will always be an array. in an ld-relay test i see that `prerequisites` can be null so that must be handled here.
here are some values stored in Redis by `ld-relay` from our dev account:
```
127.0.0.1:6379> hgetall launchdarkly:features
1) "pendo-snippet"
2) "{\"key\":\"pendo-snippet\",\"version\":2,\"on\":true,\"prerequisites\":[],\"salt\":\"cGVuZG8tc25pcHBldA==\",\"sel\":\"7bafff9319d84fd7bfaf056cfa9d08f9\",\"targets\":[{\"values\":[],\"variation\":0},{\"values\":[],\"variation\":1}],\"rules\":[],\"fallthrough\":{\"variation\":0},\"offVariation\":null,\"variations\":[true,false],\"deleted\":false}"
3) …
```
=> fix prerequisite decode notice

src/LaunchDarkly/LDClient.php
Feature flags can be anything when they are specified as multivariate.
Following this logic, the default value for a feature flag could be anything as wel.
Hinting on `boolean` here instead of `mixed` was a bit confusing.
=> Default was type hinted as boolean but can be anything.

src/LaunchDarkly/LDClient.php, tests/LDClientTest.php
`warn` is a method on the concrete Logger impl from Monolog. `warning` on the PSR LoggerInterface should be used instead.
without this change, or something like it, applications which use a logger other than Monolog are forced to write Launch Darkly factory code like this:
```
$options['logger'] = new Logger('LaunchDarkly', [
new NullHandler(),
]);
return new LDClient($apiKey, $options);
```
=> use `\Psr\Log\LoggerInterface::warning` instead of `\Monolog\Logger::warn` in `\LaunchDarkly\LDClient`

src/LaunchDarkly/LDDFeatureRequester.php, tests/LDDFeatureRequesterTest.php
allow Predis\Client to be overridden via parameter. this will allow consumers to factory their own Client with different Connection backends, Sentinel support, etc.
=> allow Predis\Client to be overridden in LDDFeatureRequester

src/LaunchDarkly/LDClient.php
allow feature-requester to be injected into the client rather than instantiated in the client controller by configurable class name. both are supported.
=> allow feature-requester to be injected into the client

src/LaunchDarkly/FeatureFlag.php
Fixing #74
Whenever the `target` field is null, should be setted as an empty array to satisfy the method signature.
=> Set target field to empty array whenever is null

src/LaunchDarkly/FeatureFlag.php
Add a guard to `FeatureFlag` in case `$v['rules']` happens to be null.
=> Ensure that FeatureFlag _rules is non-null

src/LaunchDarkly/FeatureFlag.php
Add a guard to FeatureFlag in case `$v['variations']` happens to be null.
=> Ensure that FeatureFlag _variations is non-null

README.md, composer.json, composer.lock, src/LaunchDarkly/GuzzleFeatureRequester.php
This PR resolves #65, for a better out-of-the-box experience with the PHP SDK. Dependency suggestions are properly added in `composer.json`, and `kevinrob/guzzle-cache-middleware` is no longer required (although still recommended, and an info notice is logged if it can't be found).
=> Add dependency suggestions and don't require kevinrob/guzzle-cache-middleware

src/LaunchDarkly/EventProcessor.php
hi Team,
my org ran into an issue with shell/exec duplicating connections (e.g. to db/cache) because of PHP's Apache module fork implementation which duplicates file descriptors.
here's an old bug report (from 2003) which is unlikely to be resolved:
https://bugs.php.net/bug.php?id=15529
it will likely be useful to us if we can override curl, without messing with system env. i thought this request might be useful to others as well.
=> allow curl to be overridden.

src/LaunchDarkly/LDClient.php
As per this https://github.com/Kevinrob/guzzle-cache-middleware/blob/v1.5.2/src/Strategy/PublicCacheStrategy.php#L6
the proper class is `Kevinrob\GuzzleCache\Storage\CacheStorageInterface`
=> Fix class of LDClient::__construct cache option

src/LaunchDarkly/EventProcessor.php, src/LaunchDarkly/LDClient.php
I integrated this package using a Service Provider with Laravel, but the events are never sent when using the `track()` or `identify()` method, as the EventPublisher is never destroyed (as it is kept in the Service Container for further usage).
Allowing access to the `flush()` method via the LDClient will allow manual trigger of event publication.
=> Public access to flush method

src/LaunchDarkly/EventProcessor.php
Fixing PSR2 standards. Will fix for other files once this is merged.
=> Fixing PSR2 standards

src/LaunchDarkly/VariationOrRollout.php
When we bucket for rollouts, we do so by passing the account id associated with the user, which is an integer. Without the ability to pass the bucketing attribute as an integer, we must always cast the int to a string, which is cumbersome and may also cause broader issues because if passed as an int or anything that is not a string, it just gets ignored.
I also wanted to suggest that this be applied to all SDK's for consistency.
=> Allow bucketing attributes to be integers

src/LaunchDarkly/ApcLDDFeatureRequester.php, src/LaunchDarkly/CurlEventPublisher.php, src/LaunchDarkly/EvaluationException.php, src/LaunchDarkly/EventPublisher.php, src/LaunchDarkly/FeatureFlag.php, src/LaunchDarkly/FeatureRequester.php, src/LaunchDarkly/GuzzleEventPublisher.php, src/LaunchDarkly/GuzzleFeatureRequester.php, src/LaunchDarkly/LDClient.php, src/LaunchDarkly/LDDFeatureRequester.php, src/LaunchDarkly/LDUser.php, src/LaunchDarkly/LDUserBuilder.php, src/LaunchDarkly/Operators.php, src/LaunchDarkly/Util.php
Formatting and fixes as per PSR 2 standards
=> PSR 2 standards 

composer.json
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.
=> Fix: Keep packages sorted

src/LaunchDarkly/Util.php
This PR
💁‍♂️ For reference, see http://php.net/manual/en/datetime.gettimestamp.php.
=> Fix: Case mismatch in method call

src/LaunchDarkly/GuzzleFeatureRequester.php
=> Fix: Move argument to method call

phpunit.xml
This PR
💁‍♂️ The advantage of referencing the schema is auto-completion in IDEs, and also pointing out inconsistencies with the underlying schema. Referencing the schema installed with `composer` has the advantage that there is no need to hard-code the reference to a specific version.
=> Enhancement: Reference phpunit schema as installed with composer

phpunit.xml, tests/FeatureFlagTest.php, tests/LDClientTest.php, tests/LDUserTest.php, tests/SemanticVersionTest.php
=> Fix: Risky tests

.circleci/config.yml, composer.lock
This PR
Follows #95.
Follows #97.
💁‍♂️ Running
```
$ composer validate
```
on current `master` yields
```
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
./composer.json is valid
```
Unfortunately, this was caused in #97, when I manually (🤦‍♂️) sorted the packages.
An attempt to fix this by running
```
$ composer update --lock
```
yielded
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.38) does not satisfy that requirement.
- doctrine/annotations v1.4.0 requires php ^5.6 || …
```
=> Fix: Validation fails for composer.json

src/LaunchDarkly/LDUser.php
The protected $anonyomus field results in a public $anonymous field being added whenever someone builds an LDUser that is anonymous. Fixing the spelling will bring that back to protected.
=> Update spelling of anonymous property of LDUser

.circleci/config.yml, src/LaunchDarkly/Impl/Integrations/PHPRedisFeatureRequester.php, src/LaunchDarkly/Integrations/PHPRedis.php, tests/PHPRedisFeatureRequesterTest.php
This PR adds [PHPRedis](https://github.com/phpredis/phpredis) as a Feature Requester option. 
The goal behind this is to allow the library to use persistent connections, avoiding the overhead of reconnecting to the Redis server on each request.
=> Add phpredis FeatureRequester

composer.json
Allow `monolog/monolog:^2.0` to be required as dependency next to its `monolog/monolog:^1.6` version.
**Additional context**
As a developer I want the latest Monolog dependency to be installed in projects where I use `launchdarkly/php-server-sdk`.
=> P: As a developer I want to be up-to-date with the latest Monolog dependency

src/LaunchDarkly/Impl/NullEventProcessor.php
**Related issues**
None
I've corrected the namespace for NullEventProcessor to match its place in the folder structure.
**Describe alternatives you've considered**
None
**Additional context**
Composer 1.10 began emitting this notice about version 3.7.1. This issue also exists in master.
```
Deprecation Notice: Class LaunchDarkly\NullEventProcessor located in ./vendor/launchdarkly/server-sdk/src/LaunchDarkly/Impl/NullEventProcessor.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```
=> fix namespace on dummy implementation to match PSR-4

src/LaunchDarkly/Impl/Integrations/PHPRedisFeatureRequester.php
**Related issues**
https://github.com/launchdarkly/php-server-sdk/issues/142
It sets the $this->_connection parameter in `\LaunchDarkly\Impl\Integrations\PHPRedisFeatureRequester`, but the class uses `$this->_redisInstance`.
I've renamed the parameter set in the constructor accordingly.
=> Fix setting a Redis instance via config

src/LaunchDarkly/Impl/Integrations/PHPRedisFeatureRequester.php
**Related issues**
#150
Prefixing `Redis` with a backslash to make it `\Redis` will resolve the issue, as explained in #150.
**Describe alternatives you've considered**
N/A
**Additional context**
I [did try writing a test](https://github.com/CameronHall/php-server-sdk/commit/a733ecc96c5e9f646f842a6e0fbf583d06283bf0#diff-71ff3b10ed22ffc31b1524c45b984854be92ae14590edf19b99b8a1deb78b0a3). Unfortunately, it kept failing on PHP 7.0 and 7.1. I stuffed about with it for a little while but I think it's time for bed 🥱
=> Fix bug with providing Redis Client

src/LaunchDarkly/Integrations/TestData.php, tests/Integrations/TestDataTest.php
- [Y] I have added test coverage for new or changed functionality
- [Y] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [Y] I have validated my changes against all supported platform versions
**Related issues**
Provide links to any issues in this repository or elsewhere relating to this pull request.
- fix for https://github.com/launchdarkly/php-server-sdk/issues/160
- in TestData::update when flag is being copied from previous version - use setVersion rather than ['version'] to avoid generated error
Provide a clear and concise description of what you expect to happen.
- this allows the changed flag to be updated correctly without error and the new …
=> Issue #160 - use setVersion on update of a changed flag

src/LaunchDarkly/LDClient.php
The warning message says what is going wrong, but not for what it is going wrong.
Adding a `flag` context value will help finding out which exact feature flag is having an invalid context
**Describe alternatives you've considered**
We could add this to the message but it is always better to use the logging context, see [PSR-3](https://www.php-fig.org/psr/psr-3/#13-context)
=> Log flag when invalid context was used for flag evaluation

src/LaunchDarkly/Impl/Util.php
Various logging tools can generate a stack trace based on the exception being on the 'exception' key in the logging context. See [PSR-3](https://www.php-fig.org/psr/psr-3/#13-context)
**Describe alternatives you've considered**
We could keep the `debug` log but since this introduces duplicate logging and does not provide a browsable context of the exception, it is better to remove this.
I am a bit conflicted about keeping `$e->getMessage()` as part of the error message, since this becomes redundant with the same reason as before, many logging tools simply use the exception on the logging context already and use it as a message.
=> Improve error logging

src/LaunchDarkly/Impl/Integrations/CurlEventPublisher.php
=> fix: Replace deprecated utf8_encode usage
